import path from "node:path";
import type { SceneArtboard } from "@motion-mcp/scene-graph";
import {
  type AssetInfo,
  type FileChange,
  type GenerateAnimationOptions,
  type MotionPlanItem,
  nowIso
} from "@motion-mcp/shared-types";

export function emitUnityAnimation(input: {
  planItem: MotionPlanItem;
  asset?: AssetInfo;
  options: GenerateAnimationOptions;
  scene?: SceneArtboard;
}): FileChange[] {
  const className = safeCSharpClassName(input.asset?.path ?? input.planItem.file);
  return [
    {
      path: `.motion-mcp/generated/unity/${className}.cs`,
      mode: "create",
      content: `using UnityEngine;
using UnityEngine.EventSystems;

/// <summary>
/// Generated by motion-mcp on ${nowIso()}.
/// Prompt: ${escapeComment(input.planItem.interactionIdea)}
/// Beta target: Unity output uses a host-code state machine. DOTween can replace the coroutine tween path when installed.
${input.scene ? `/// SceneDoc artboard: ${input.scene.artboardId} (${Object.keys(input.scene.clips).length} clips, states: ${input.scene.stateMachines[0]?.states.map((s2) => s2.name).join(", ") ?? "none"}).` : ""}
/// </summary>
public sealed class ${className} : MonoBehaviour, IPointerEnterHandler, IPointerExitHandler, IPointerDownHandler, IPointerUpHandler, IPointerClickHandler
{
    public enum MotionState { Idle, Hover, Pressed, Active, Success, Error, Disabled }
    public enum MotionEvent { PointerEnter, PointerLeave, PressIn, PressOut, Activate, Success, Error, Reset }

    [SerializeField] private MotionState initialState = MotionState.Idle;
    [SerializeField] private float hoverScale = 1.035f;
    [SerializeField] private float pressScale = 0.965f;
    [SerializeField] private float duration = 0.18f;

    private MotionState state;
    private Vector3 originalScale;
    private Coroutine activeTween;

    private void Awake()
    {
        state = initialState;
        originalScale = transform.localScale;
    }

    public void Send(MotionEvent motionEvent)
    {
        if (state == MotionState.Disabled) return;

        switch (motionEvent)
        {
            case MotionEvent.PointerEnter:
                state = state == MotionState.Active ? MotionState.Active : MotionState.Hover;
                TweenScale(originalScale * hoverScale);
                break;
            case MotionEvent.PointerLeave:
                state = state == MotionState.Active ? MotionState.Active : MotionState.Idle;
                TweenScale(state == MotionState.Active ? originalScale * hoverScale : originalScale);
                break;
            case MotionEvent.PressIn:
                state = MotionState.Pressed;
                TweenScale(originalScale * pressScale);
                break;
            case MotionEvent.PressOut:
                state = MotionState.Hover;
                TweenScale(originalScale * hoverScale);
                break;
            case MotionEvent.Activate:
                state = MotionState.Active;
                TweenScale(originalScale * hoverScale);
                break;
            case MotionEvent.Success:
                state = MotionState.Success;
                TweenScale(originalScale * 1.08f, () => TweenScale(originalScale));
                break;
            case MotionEvent.Error:
                state = MotionState.Error;
                TweenShake();
                break;
            case MotionEvent.Reset:
                state = MotionState.Idle;
                TweenScale(originalScale);
                break;
        }
    }

    public void OnPointerEnter(PointerEventData eventData) => Send(MotionEvent.PointerEnter);
    public void OnPointerExit(PointerEventData eventData) => Send(MotionEvent.PointerLeave);
    public void OnPointerDown(PointerEventData eventData) => Send(MotionEvent.PressIn);
    public void OnPointerUp(PointerEventData eventData) => Send(MotionEvent.PressOut);
    public void OnPointerClick(PointerEventData eventData) => Send(MotionEvent.Activate);

    private void TweenScale(Vector3 target, System.Action onComplete = null)
    {
        if (activeTween != null) StopCoroutine(activeTween);
        activeTween = StartCoroutine(TweenScaleRoutine(target, onComplete));
    }

    private void TweenShake()
    {
        if (activeTween != null) StopCoroutine(activeTween);
        activeTween = StartCoroutine(TweenShakeRoutine());
    }

    private System.Collections.IEnumerator TweenScaleRoutine(Vector3 target, System.Action onComplete)
    {
        var start = transform.localScale;
        var elapsed = 0f;
        while (elapsed < duration)
        {
            elapsed += Time.unscaledDeltaTime;
            var t = Mathf.Clamp01(elapsed / duration);
            t = 1f - Mathf.Pow(1f - t, 3f);
            transform.localScale = Vector3.LerpUnclamped(start, target, t);
            yield return null;
        }
        transform.localScale = target;
        onComplete?.Invoke();
    }

    private System.Collections.IEnumerator TweenShakeRoutine()
    {
        var start = transform.localPosition;
        var elapsed = 0f;
        while (elapsed < duration * 1.8f)
        {
            elapsed += Time.unscaledDeltaTime;
            var strength = 3f * (1f - Mathf.Clamp01(elapsed / (duration * 1.8f)));
            transform.localPosition = start + new Vector3(Mathf.Sin(elapsed * 70f) * strength, 0, 0);
            yield return null;
        }
        transform.localPosition = start;
    }
}
`
    }
  ];
}

function safeCSharpClassName(file: string): string {
  const base = path.basename(file, path.extname(file));
  const pascal = base
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");
  return `Motion${pascal || "Generated"}`;
}

function escapeComment(value: string): string {
  return value.replace(/\*\//g, "* /").replace(/\r?\n/g, " ");
}
