import path from "node:path";
import type { SceneArtboard, SceneClip } from "@motion-mcp/scene-graph";
import {
  type AssetInfo,
  type FileChange,
  type GenerateAnimationOptions,
  type MotionPlanItem,
  nowIso
} from "@motion-mcp/shared-types";

export function emitUnityAnimation(input: {
  planItem: MotionPlanItem;
  asset?: AssetInfo;
  options: GenerateAnimationOptions;
  scene?: SceneArtboard;
}): FileChange[] {
  const className = safeCSharpClassName(input.asset?.path ?? input.planItem.file);
  const is3d = input.scene?.is3d || !!input.scene?.rig?.bones.some((b) => b.origin3d !== undefined);
  const files: FileChange[] = [];

  if (is3d && input.scene) {
    // Emit 3D skeletal animation controller and Unity .anim YAML clips
    files.push({
      path: `.motion-mcp/generated/unity/${className}Controller.cs`,
      mode: "create",
      content: generateUnity3dController(className, input)
    });

    for (const [clipId, clip] of Object.entries(input.scene.clips)) {
      const clipName = clip.name || clipId;
      const safeName = safeCSharpClassName(clipName);
      files.push({
        path: `.motion-mcp/generated/unity/${className}_${safeName}.anim`,
        mode: "create",
        content: generateUnityAnimationClipYaml(clip, input.scene)
      });
    }

    return files;
  }

  // 2D UI Animation Fallback (preserves original UI behavior)
  files.push({
    path: `.motion-mcp/generated/unity/${className}.cs`,
    mode: "create",
    content: generateUnity2dMonoBehaviour(className, input)
  });

  return files;
}

function generateUnity3dController(
  className: string,
  input: { planItem: MotionPlanItem; scene?: SceneArtboard }
): string {
  const clips = input.scene ? Object.values(input.scene.clips) : [];
  const stateNames = input.scene?.stateMachines[0]?.states.map((s) => s.name) ?? clips.map((c) => c.name);

  return `using UnityEngine;

/// <summary>
/// Generated by motion-mcp on ${nowIso()}.
/// Prompt: ${escapeComment(input.planItem.interactionIdea)}
/// 3D Skeletal Animation Controller with Mecanim Humanoid & Generic Rig support.
/// </summary>
[RequireComponent(typeof(Animator))]
public sealed class ${className}Controller : MonoBehaviour
{
    [Header("Animation Settings")]
    [SerializeField] private string defaultState = "${stateNames[0] || "Idle"}";
    [SerializeField] private float crossFadeDuration = 0.25f;

    private Animator animator;

    private void Awake()
    {
        animator = GetComponent<Animator>();
    }

    private void Start()
    {
        if (!string.IsNullOrEmpty(defaultState))
        {
            PlayState(defaultState);
        }
    }

    public void PlayState(string stateName)
    {
        if (animator == null) return;
        animator.CrossFade(stateName, crossFadeDuration);
    }

${clips
  .map(
    (c) => `    public void Play${safeCSharpClassName(c.name || "Clip")}() => PlayState("${c.name || "Clip"}");`
  )
  .join("\n")}
}
`;
}

function generateUnityAnimationClipYaml(clip: SceneClip, scene: SceneArtboard): string {
  const duration = (clip.durationMs / 1000).toFixed(4);
  const sampleRate = 30;

  let yaml = `%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!74 &7400000
AnimationClip:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_Name: ${clip.name || "MotionClip"}
  serializedVersion: 7
  m_Legacy: 0
  m_Compressed: 0
  m_UseHighQualityCurve: 1
  m_RotationCurves:
`;

  // Process rotation tracks
  for (const track of clip.tracks) {
    if (track.property === "quaternion") {
      const boneName = track.targetPart.replace(/^bone_/, "");
      yaml += `  - curve:\n      serializedVersion: 2\n      m_Curve:\n`;
      for (const key of track.keys) {
        const time = (key.t * (clip.durationMs / 1000)).toFixed(4);
        const q = Array.isArray(key.value) ? key.value : [0, 0, 0, 1];
        yaml += `      - serializedVersion: 3\n        time: ${time}\n        value: {x: ${q[0]}, y: ${q[1]}, z: ${q[2]}, w: ${q[3]}}\n        inSlope: {x: 0, y: 0, z: 0, w: 0}\n        outSlope: {x: 0, y: 0, z: 0, w: 0}\n        tangentMode: 0\n        weightedMode: 0\n`;
      }
      yaml += `      m_PreInfinity: 2\n      m_PostInfinity: 2\n      m_RotationOrder: 4\n    path: ${boneName}\n`;
    }
  }

  yaml += `  m_CompressedRotationCurves: []
  m_EulerCurves: []
  m_PositionCurves: []
  m_ScaleCurves: []
  m_FloatCurves: []
  m_PPtrCurves: []
  m_SampleRate: ${sampleRate}
  m_WrapMode: ${clip.loop ? 2 : 0}
  m_Bounds:
    m_Center: {x: 0, y: 1, z: 0}
    m_Extent: {x: 1, y: 1, z: 1}
  m_ClipBindingConstant:
    genericBindings: []
    pptrCurveMapping: []
  m_AnimationClipSettings:
    serializedVersion: 2
    m_AdditiveReferencePoseClip: {fileID: 0}
    m_AdditiveReferencePoseTime: 0
    m_StartTime: 0
    m_StopTime: ${duration}
    m_OrientationOffsetY: 0
    m_Level: 0
    m_CycleOffset: 0
    m_HasAdditiveReferencePose: 0
    m_LoopTime: ${clip.loop ? 1 : 0}
    m_LoopBlend: 0
    m_LoopBlendOrientation: 0
    m_LoopBlendPositionY: 0
    m_LoopBlendPositionXZ: 0
    m_KeepOriginalOrientation: 0
    m_KeepOriginalPositionY: 1
    m_KeepOriginalPositionXZ: 0
    m_HeightFromFeet: 0
    m_Mirror: 0
  m_EditorCurves: []
  m_EulerEditorCurves: []
  m_HasGenericRootTransform: 0
  m_HasMotionFloatCurves: 0
  m_Events: []
`;

  return yaml;
}

function generateUnity2dMonoBehaviour(
  className: string,
  input: { planItem: MotionPlanItem; scene?: SceneArtboard }
): string {
  return `using UnityEngine;
using UnityEngine.EventSystems;

/// <summary>
/// Generated by motion-mcp on ${nowIso()}.
/// Prompt: ${escapeComment(input.planItem.interactionIdea)}
/// 2D UI Tween Controller.
${input.scene ? `/// SceneDoc artboard: ${input.scene.artboardId} (${Object.keys(input.scene.clips).length} clips, states: ${input.scene.stateMachines[0]?.states.map((s2) => s2.name).join(", ") ?? "none"}).` : ""}
/// </summary>
public sealed class ${className} : MonoBehaviour, IPointerEnterHandler, IPointerExitHandler, IPointerDownHandler, IPointerUpHandler, IPointerClickHandler
{
    public enum MotionState { Idle, Hover, Pressed, Active, Success, Error, Disabled }
    public enum MotionEvent { PointerEnter, PointerLeave, PressIn, PressOut, Activate, Success, Error, Reset }

    [SerializeField] private MotionState initialState = MotionState.Idle;
    [SerializeField] private float hoverScale = 1.035f;
    [SerializeField] private float pressScale = 0.965f;
    [SerializeField] private float duration = 0.18f;

    private MotionState state;
    private Vector3 originalScale;
    private Coroutine activeTween;

    private void Awake()
    {
        state = initialState;
        originalScale = transform.localScale;
    }

    public void Send(MotionEvent motionEvent)
    {
        if (state == MotionState.Disabled) return;

        switch (motionEvent)
        {
            case MotionEvent.PointerEnter:
                state = state == MotionState.Active ? MotionState.Active : MotionState.Hover;
                TweenScale(originalScale * hoverScale);
                break;
            case MotionEvent.PointerLeave:
                state = state == MotionState.Active ? MotionState.Active : MotionState.Idle;
                TweenScale(state == MotionState.Active ? originalScale * hoverScale : originalScale);
                break;
            case MotionEvent.PressIn:
                state = MotionState.Pressed;
                TweenScale(originalScale * pressScale);
                break;
            case MotionEvent.PressOut:
                state = MotionState.Hover;
                TweenScale(originalScale * hoverScale);
                break;
            case MotionEvent.Activate:
                state = MotionState.Active;
                TweenScale(originalScale * hoverScale);
                break;
            case MotionEvent.Success:
                state = MotionState.Success;
                TweenScale(originalScale * 1.08f, () => TweenScale(originalScale));
                break;
            case MotionEvent.Error:
                state = MotionState.Error;
                TweenShake();
                break;
            case MotionEvent.Reset:
                state = MotionState.Idle;
                TweenScale(originalScale);
                break;
        }
    }

    public void OnPointerEnter(PointerEventData eventData) => Send(MotionEvent.PointerEnter);
    public void OnPointerExit(PointerEventData eventData) => Send(MotionEvent.PointerLeave);
    public void OnPointerDown(PointerEventData eventData) => Send(MotionEvent.PressIn);
    public void OnPointerUp(PointerEventData eventData) => Send(MotionEvent.PressOut);
    public void OnPointerClick(PointerEventData eventData) => Send(MotionEvent.Activate);

    private void TweenScale(Vector3 target, System.Action onComplete = null)
    {
        if (activeTween != null) StopCoroutine(activeTween);
        activeTween = StartCoroutine(TweenScaleRoutine(target, onComplete));
    }

    private void TweenShake()
    {
        if (activeTween != null) StopCoroutine(activeTween);
        activeTween = StartCoroutine(TweenShakeRoutine());
    }

    private System.Collections.IEnumerator TweenScaleRoutine(Vector3 target, System.Action onComplete)
    {
        var start = transform.localScale;
        var elapsed = 0f;
        while (elapsed < duration)
        {
            elapsed += Time.unscaledDeltaTime;
            var t = Mathf.Clamp01(elapsed / duration);
            t = 1f - Mathf.Pow(1f - t, 3f);
            transform.localScale = Vector3.LerpUnclamped(start, target, t);
            yield return null;
        }
        transform.localScale = target;
        onComplete?.Invoke();
    }

    private System.Collections.IEnumerator TweenShakeRoutine()
    {
        var start = transform.localPosition;
        var elapsed = 0f;
        while (elapsed < duration * 1.8f)
        {
            elapsed += Time.unscaledDeltaTime;
            var strength = 3f * (1f - Mathf.Clamp01(elapsed / (duration * 1.8f)));
            transform.localPosition = start + new Vector3(Mathf.Sin(elapsed * 70f) * strength, 0, 0);
            yield return null;
        }
        transform.localPosition = start;
    }
}
`;
}

function safeCSharpClassName(file: string): string {
  const base = path.basename(file, path.extname(file));
  const pascal = base
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");
  return `Motion${pascal || "Generated"}`;
}

function escapeComment(value: string): string {
  return value.replace(/\*\//g, "* /").replace(/\r?\n/g, " ");
}
