import path from "node:path";
import type { SceneArtboard } from "@motion-mcp/scene-graph";
import {
  type AssetInfo,
  type FileChange,
  type GenerateAnimationOptions,
  type MotionPlanItem,
  nowIso
} from "@motion-mcp/shared-types";

export function emitFlutterAnimation(input: {
  planItem: MotionPlanItem;
  asset?: AssetInfo;
  options: GenerateAnimationOptions;
  scene?: SceneArtboard;
}): FileChange[] {
  const sceneStates = input.scene?.stateMachines[0]?.states
    .map((state) => state.name.toLowerCase().replace(/[^a-z0-9]+/g, ""))
    .filter(Boolean) ?? [];
  const className = safeDartClassName(input.asset?.path ?? input.planItem.file);
  return [
    {
      path: `.motion-mcp/generated/flutter/${toSnake(className)}.dart`,
      mode: "create",
      content: `import 'package:flutter/material.dart';

/// Generated by motion-mcp on ${nowIso()}.
/// Prompt: ${escapeComment(input.planItem.interactionIdea)}
/// Beta target: Flutter output uses host-code state machines and AnimatedBuilder.${input.scene ? `\n/// SceneDoc artboard: ${input.scene.artboardId} (${Object.keys(input.scene.clips).length} clips).` : ""}
enum ${className}MotionState { ${sceneStates.length > 0 ? sceneStates.join(", ") : "idle, hover, pressed, active, success, error, disabled"} }
enum ${className}MotionEvent { pointerEnter, pointerLeave, pressIn, pressOut, activate, success, error, reset }

class ${className} extends StatefulWidget {
  const ${className}({
    super.key,
    required this.child,
    this.active = false,
    this.motionState,
    this.duration = const Duration(milliseconds: 620),
  });

  final Widget child;
  final bool active;
  final ${className}MotionState? motionState;
  final Duration duration;

  @override
  State<${className}> createState() => _${className}State();
}

class _${className}State extends State<${className}> with SingleTickerProviderStateMixin {
  late final AnimationController _controller;
  late final Animation<double> _scale;
  late final Animation<double> _lift;
  late ${className}MotionState _state;

  ${className}MotionState get state => widget.motionState ?? _state;

  @override
  void initState() {
    super.initState();
    _state = widget.active ? ${className}MotionState.active : ${className}MotionState.idle;
    _controller = AnimationController(vsync: this, duration: widget.duration);
    _scale = TweenSequence<double>([
      TweenSequenceItem(tween: Tween(begin: 1, end: 0.97).chain(CurveTween(curve: Curves.easeOutCubic)), weight: 20),
      TweenSequenceItem(tween: Tween(begin: 0.97, end: 1.04).chain(CurveTween(curve: Curves.easeOutBack)), weight: 45),
      TweenSequenceItem(tween: Tween(begin: 1.04, end: 1).chain(CurveTween(curve: Curves.easeOutCubic)), weight: 35),
    ]).animate(_controller);
    _lift = Tween<double>(begin: 0, end: -4).chain(CurveTween(curve: Curves.easeOutCubic)).animate(_controller);
    if (widget.active) _controller.forward();
  }

  void send(${className}MotionEvent event) {
    if (widget.motionState != null || state == ${className}MotionState.disabled) return;
    setState(() {
      switch (event) {
        case ${className}MotionEvent.pointerEnter:
          _state = widget.active ? ${className}MotionState.active : ${className}MotionState.hover;
        case ${className}MotionEvent.pointerLeave:
          _state = widget.active ? ${className}MotionState.active : ${className}MotionState.idle;
        case ${className}MotionEvent.pressIn:
          _state = ${className}MotionState.pressed;
        case ${className}MotionEvent.pressOut:
          _state = widget.active ? ${className}MotionState.active : ${className}MotionState.hover;
        case ${className}MotionEvent.activate:
          _state = ${className}MotionState.active;
        case ${className}MotionEvent.success:
          _state = ${className}MotionState.success;
        case ${className}MotionEvent.error:
          _state = ${className}MotionState.error;
        case ${className}MotionEvent.reset:
          _state = ${className}MotionState.idle;
      }
    });
    if (state != ${className}MotionState.idle) _controller.forward(from: 0);
  }

  @override
  void didUpdateWidget(covariant ${className} oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.active && !oldWidget.active) send(${className}MotionEvent.activate);
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final disableAnimations = MediaQuery.maybeOf(context)?.disableAnimations ?? false;
    final disabled = state == ${className}MotionState.disabled;
    if (disableAnimations) return Opacity(opacity: disabled ? .48 : 1, child: widget.child);

    return MouseRegion(
      onEnter: (_) => send(${className}MotionEvent.pointerEnter),
      onExit: (_) => send(${className}MotionEvent.pointerLeave),
      child: GestureDetector(
        onTapDown: (_) => send(${className}MotionEvent.pressIn),
        onTapUp: (_) => send(${className}MotionEvent.pressOut),
        onTapCancel: () => send(${className}MotionEvent.reset),
        child: AnimatedBuilder(
          animation: _controller,
          builder: (context, child) {
            final shake = state == ${className}MotionState.error ? (1 - _controller.value) * 3 : 0;
            return Opacity(
              opacity: disabled ? .48 : 1,
              child: Transform.translate(
                offset: Offset(shake, state == ${className}MotionState.hover || state == ${className}MotionState.active ? _lift.value : 0),
                child: Transform.scale(
                  scale: state == ${className}MotionState.idle ? 1 : _scale.value,
                  child: child,
                ),
              ),
            );
          },
          child: widget.child,
        ),
      ),
    );
  }
}
`
    }
  ];
}

function safeDartClassName(file: string): string {
  const base = path.basename(file, path.extname(file));
  const pascal = base
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");
  return `Motion${pascal || "Generated"}`;
}

function toSnake(value: string): string {
  return value.replace(/[A-Z]/g, (letter, index) => `${index ? "_" : ""}${letter.toLowerCase()}`);
}

function escapeComment(value: string): string {
  return value.replace(/\r?\n/g, " ");
}
