import path from "node:path";
import {
  STANDARD_MOTION_EVENTS,
  STANDARD_MOTION_STATES,
  type AssetInfo,
  type FileChange,
  type GenerateAnimationOptions,
  type MotionPlanItem,
  nowIso
} from "@motion-mcp/shared-types";

export function emitReactAnimation(input: {
  planItem: MotionPlanItem;
  asset?: AssetInfo;
  options: GenerateAnimationOptions;
}): FileChange[] {
  const componentName = safeComponentName(input.asset?.path ?? input.planItem.file);
  const filePath = `.motion-mcp/generated/react/${componentName}.tsx`;
  const content = input.asset?.type === "svg" && input.asset.pathTree
    ? emitAnimatedSvgComponent(componentName, input)
    : emitMotionEnhancerComponent(componentName, input);
  return [
    {
      path: filePath,
      mode: "create",
      content
    }
  ];
}

function emitAnimatedSvgComponent(
  componentName: string,
  input: {
    planItem: MotionPlanItem;
    asset?: AssetInfo;
    options: GenerateAnimationOptions;
  }
): string {
  const asset = input.asset;
  const nodes = asset?.pathTree?.flatMap(flattenNodes).filter((node) =>
    ["path", "circle", "rect", "ellipse", "polygon", "polyline", "line"].includes(node.tag)
  ) ?? [];
  const viewBox = asset?.dimensions?.viewBox ?? "0 0 160 160";
  const width = asset?.dimensions?.width ?? 120;
  const height = asset?.dimensions?.height ?? 120;
  const shapes = nodes.length > 0
    ? nodes.map((node, index) => svgNodeToMotion(node, index)).join("\n")
    : "        <motion.path d=\"M80 18C114 18 142 46 142 80S114 142 80 142 18 114 18 80 46 18 80 18Z\" fill=\"none\" stroke=\"currentColor\" strokeWidth={8} variants={partVariant(0)} />";

  return `"use client";

import * as React from "react";
import { motion, useReducedMotion, type Variants } from "framer-motion";

type MotionState = ${STANDARD_MOTION_STATES.map((state) => JSON.stringify(state)).join(" | ")};
type MotionEvent = ${STANDARD_MOTION_EVENTS.map((event) => JSON.stringify(event)).join(" | ")};

const transition = { type: "spring", stiffness: 380, damping: 30 } as const;

/**
 * Generated by motion-mcp on ${nowIso()}.
 * Prompt: ${escapeComment(input.planItem.interactionIdea)}
 * Source asset: ${asset?.path ?? "unknown"}
 * Runtime: host-code state machine + Framer Motion SVG parts.
 */
export interface ${componentName}Props extends React.SVGProps<SVGSVGElement> {
  active?: boolean;
  motionState?: MotionState;
  onMotionStateChange?: (state: MotionState, event: MotionEvent) => void;
}

export function use${componentName}StateMachine(active = false, controlledState?: MotionState) {
  const [state, setState] = React.useState<MotionState>(active ? "active" : "idle");

  React.useEffect(() => {
    if (controlledState) setState(controlledState);
  }, [controlledState]);

  React.useEffect(() => {
    if (!controlledState) setState(active ? "active" : "idle");
  }, [active, controlledState]);

  const send = React.useCallback((event: MotionEvent) => {
    setState((current) => {
      if (current === "disabled") return current;
      switch (event) {
        case "pointerEnter": return current === "active" ? "active" : "hover";
        case "pointerLeave": return active ? "active" : "idle";
        case "pressIn": return "pressed";
        case "pressOut": return active ? "active" : "hover";
        case "activate": return "active";
        case "success": return "success";
        case "error": return "error";
        case "reset": return "idle";
        default: return current;
      }
    });
  }, [active]);

  return { state: controlledState ?? state, send };
}

export function ${componentName}({
  active = false,
  motionState,
  onMotionStateChange,
  ...props
}: ${componentName}Props) {
  const reducedMotion = useReducedMotion();
  const { state, send } = use${componentName}StateMachine(active, motionState);

  const emit = (event: MotionEvent) => {
    send(event);
    onMotionStateChange?.(state, event);
  };

  const partVariant = (index: number): Variants => ({
    idle: { opacity: 0.88, pathLength: 1, scale: 1, rotate: 0 },
    hover: reducedMotion ? { opacity: 1 } : { opacity: 1, pathLength: 1, scale: 1.012, transition: { ...transition, delay: index * 0.025 } },
    pressed: reducedMotion ? { opacity: 1 } : { opacity: 1, scale: 0.965, transition: { duration: 0.08 } },
    active: reducedMotion ? { opacity: 1 } : { opacity: 1, pathLength: 1, scale: 1.035, transition: { ...transition, delay: index * 0.035 } },
    success: reducedMotion ? { opacity: 1 } : { opacity: 1, scale: [1, 1.08, 1], rotate: [0, 1.5, 0], transition: { duration: 0.62, delay: index * 0.025 } },
    error: reducedMotion ? { opacity: 1 } : { opacity: 1, x: [0, -2, 2, -1, 0], transition: { duration: 0.34 } },
    disabled: { opacity: 0.48, scale: 1 }
  });

  return (
    <motion.svg
      viewBox="${viewBox}"
      width={${JSON.stringify(width)}}
      height={${JSON.stringify(height)}}
      role="img"
      initial={false}
      animate={state}
      onPointerEnter={() => emit("pointerEnter")}
      onPointerLeave={() => emit("pointerLeave")}
      onPointerDown={() => emit("pressIn")}
      onPointerUp={() => emit("pressOut")}
      transition={reducedMotion ? { duration: 0 } : transition}
      {...props}
    >
${shapes}
    </motion.svg>
  );
}

export default ${componentName};
`;
}

function emitMotionEnhancerComponent(
  componentName: string,
  input: {
    planItem: MotionPlanItem;
    options: GenerateAnimationOptions;
  }
): string {
  return `"use client";

import * as React from "react";
import { motion, useReducedMotion } from "framer-motion";

type MotionState = ${STANDARD_MOTION_STATES.map((state) => JSON.stringify(state)).join(" | ")};
type MotionEvent = ${STANDARD_MOTION_EVENTS.map((event) => JSON.stringify(event)).join(" | ")};

/**
 * Generated by motion-mcp on ${nowIso()}.
 * Prompt: ${escapeComment(input.planItem.interactionIdea)}
 * Runtime: host-code state machine + Framer Motion wrapper.
 */
export interface ${componentName}Props {
  children: React.ReactNode;
  active?: boolean;
  motionState?: MotionState;
  className?: string;
}

export function ${componentName}({ children, active = false, motionState, className }: ${componentName}Props) {
  const reducedMotion = useReducedMotion();
  const [localState, setLocalState] = React.useState<MotionState>(active ? "active" : "idle");
  const state = motionState ?? localState;
  const send = (event: MotionEvent) => {
    if (motionState) return;
    if (event === "pointerEnter") setLocalState(active ? "active" : "hover");
    if (event === "pointerLeave") setLocalState(active ? "active" : "idle");
    if (event === "pressIn") setLocalState("pressed");
    if (event === "pressOut") setLocalState(active ? "active" : "hover");
    if (event === "activate") setLocalState("active");
    if (event === "success") setLocalState("success");
    if (event === "error") setLocalState("error");
    if (event === "reset") setLocalState("idle");
  };

  return (
    <motion.div
      className={className}
      initial={false}
      animate={state}
      variants={{
        idle: { scale: 1, y: 0, filter: "drop-shadow(0 0 0 rgba(91, 124, 250, 0))" },
        hover: reducedMotion ? {} : { scale: 1.018, y: -2, filter: "drop-shadow(0 10px 24px rgba(91, 124, 250, 0.18))" },
        pressed: reducedMotion ? {} : { scale: 0.985, y: 0 },
        active: reducedMotion ? {} : { scale: 1.015, y: -2, filter: "drop-shadow(0 10px 24px rgba(91, 124, 250, 0.24))" },
        success: reducedMotion ? {} : { scale: [1, 1.04, 1], y: [0, -3, 0] },
        error: reducedMotion ? {} : { x: [0, -3, 3, -1, 0] },
        disabled: { opacity: 0.5 }
      }}
      onPointerEnter={() => send("pointerEnter")}
      onPointerLeave={() => send("pointerLeave")}
      onPointerDown={() => send("pressIn")}
      onPointerUp={() => send("pressOut")}
      transition={reducedMotion ? { duration: 0 } : { type: "spring", stiffness: 380, damping: 30 }}
    >
      {children}
    </motion.div>
  );
}

export default ${componentName};
`;
}

function svgNodeToMotion(node: { tag: string; attrs: Record<string, string>; semanticLabel?: string; roleGuess: string }, index: number): string {
  const tagName = `motion.${node.tag}`;
  const attrs = Object.entries(node.attrs)
    .filter(([key]) => !["id", "class", "data-name"].includes(key))
    .map(([key, value]) => `${camelSvgAttr(key)}=${JSON.stringify(sanitizeSvgValue(value))}`)
    .join(" ");
  const label = node.semanticLabel ?? node.roleGuess;
  return `        {/* ${escapeComment(label)} */}
        <${tagName} ${attrs} variants={partVariant(${index})} />`;
}

function flattenNodes<T extends { children: T[] }>(node: T): T[] {
  return [node, ...node.children.flatMap(flattenNodes)];
}

function camelSvgAttr(attr: string): string {
  return attr.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase());
}

function sanitizeSvgValue(value: string): string {
  if (/^url\(#/.test(value)) return "currentColor";
  return value;
}

function safeComponentName(file: string): string {
  const base = path.basename(file, path.extname(file));
  const pascal = base
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");
  return `Motion${pascal || "Generated"}`;
}

function escapeComment(value: string): string {
  return value.replace(/\*\//g, "* /").replace(/\r?\n/g, " ");
}
