import path from "node:path";
import type { SceneArtboard } from "@motion-mcp/scene-graph";
import { type FileChange, type MotionPlanItem, type GenerateAnimationOptions, nowIso } from "@motion-mcp/shared-types";

export function emitR3fAnimation(input: {
  planItem: MotionPlanItem;
  asset?: { path: string };
  options: GenerateAnimationOptions;
  scene?: SceneArtboard;
}): FileChange[] {
  const componentName = safeComponentName(input.asset?.path ?? input.planItem.file);
  const hasScene = !!input.scene;
  const is3d = input.scene?.is3d ?? false;
  const clips = input.scene ? Object.values(input.scene.clips) : [];
  const rig = input.scene?.rig;

  // Build AnimationClip construction code from SceneDoc tracks
  const clipCode = clips.map((clip, i) => {
    const trackLines = clip.tracks.map((track) => {
      if (track.property === "quaternion") {
        const times = track.keys.map((k) => `${(k.t * clip.durationMs / 1000).toFixed(3)}`).join(", ");
        const values = track.keys.map((k) => {
          const v = Array.isArray(k.value) ? k.value : [0, 0, 0, 1];
          return v.map((n) => (typeof n === "number" ? n.toFixed(4) : "0")).join(", ");
        }).join(", ");
        return `    new THREE.QuaternionKeyframeTrack("${track.targetPart}.quaternion", [${times}], [${values}])`;
      }
      const propMap: Record<string, string> = {
        translateX: "position[0]", translateY: "position[1]", translateZ: "position[2]",
        rotateX: "rotation[0]", rotateY: "rotation[1]", rotateZ: "rotation[2]",
        scaleX: "scale[0]", scaleY: "scale[1]", scaleZ: "scale[2]",
        scale: "scale", opacity: "material.opacity"
      };
      const threeProp = propMap[track.property] ?? track.property;
      const times = track.keys.map((k) => `${(k.t * clip.durationMs / 1000).toFixed(3)}`).join(", ");
      const values = track.keys.map((k) => typeof k.value === "number" ? k.value.toFixed(4) : "0").join(", ");
      return `    new THREE.NumberKeyframeTrack("${track.targetPart}.${threeProp}", [${times}], [${values}])`;
    });
    return `const clip${i} = new THREE.AnimationClip("${clip.name}", ${(clip.durationMs / 1000).toFixed(2)}, [\n${trackLines.join(",\n")}\n]);`;
  }).join("\n\n");

  const modelUrl = input.asset?.path ?? "/models/character.glb";
  const stateNames = input.scene?.stateMachines[0]?.states.map((s) => s.name) ?? [];

  const code = `import { useEffect, useRef } from "react";
import * as THREE from "three";
import { useFrame } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";

/**
 * Generated by motion-mcp on ${nowIso()}.
 * Prompt: ${escapeStr(input.planItem.interactionIdea)}
 * SceneDoc: ${is3d ? "3D artboard" : "2D artboard"}${rig ? `, ${rig.bones.length} bones (${rig.skeletonType ?? "custom"})` : ""}
 * States: ${stateNames.join(", ") || "none"}
 */

${clipCode}

export interface ${componentName}Props {
  url?: string;
  autoPlay?: boolean;
  loop?: boolean;
  onComplete?: () => void;
}

export function ${componentName}({ url = "${modelUrl}", autoPlay = true, loop = true, onComplete }: ${componentName}Props) {
  const group = useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF(url);
  const { actions, mixer } = useAnimations([${clips.map((_, i) => `clip${i}`).join(", ")}${clips.length > 0 ? ", " : ""}...animations], group);

  useEffect(() => {
    if (!autoPlay) return;
    const action = actions["${clips[0]?.name ?? "idle"}"];
    if (!action) return;
    action.reset();
    action.setLoop(loop ? THREE.LoopRepeat : THREE.LoopOnce, loop ? Infinity : 1);
    action.clampWhenFinished = !loop;
    action.fadeIn(0.3).play();

    if (!loop && onComplete) {
      const handler = (e: { action: THREE.AnimationAction }) => {
        if (e.action === action) onComplete();
      };
      mixer.addEventListener("finished", handler);
      return () => {
        mixer.removeEventListener("finished", handler);
        action.fadeOut(0.3);
      };
    }
    return () => { action.fadeOut(0.3); };
  }, [actions, mixer, autoPlay, loop, onComplete]);

  return <primitive ref={group} object={scene} dispose={null} />;
}
`;

  return [{
    path: `.motion-mcp/generated/r3f/${componentName}.tsx`,
    mode: "create",
    content: code
  }];
}

function safeComponentName(file: string): string {
  const base = path.basename(file, path.extname(file));
  const pascal = base.replace(/[^a-zA-Z0-9]+/g, " ").split(" ").filter(Boolean)
    .map((p) => `${p.charAt(0).toUpperCase()}${p.slice(1)}`).join("");
  return `Motion${pascal || "Generated"}`;
}

function escapeStr(s: string): string {
  return s.replace(/\*/g, "").replace(/\n/g, " ").slice(0, 200);
}
