import path from "node:path";
import type { SceneArtboard } from "@motion-mcp/scene-graph";
import { type FileChange, type MotionPlanItem, type GenerateAnimationOptions, nowIso } from "@motion-mcp/shared-types";

export function emitVanillaThreejsAnimation(input: {
  planItem: MotionPlanItem;
  asset?: { path: string };
  options: GenerateAnimationOptions;
  scene?: SceneArtboard;
}): FileChange[] {
  const moduleName = safeModuleName(input.asset?.path ?? input.planItem.file);
  const clips = input.scene ? Object.values(input.scene.clips) : [];

  const clipCode = clips.map((clip, i) => {
    const trackLines = clip.tracks.map((track) => {
      if (track.property === "quaternion") {
        const times = track.keys.map((k) => (k.t * clip.durationMs / 1000).toFixed(3)).join(", ");
        const values = track.keys.map((k) => {
          const v = Array.isArray(k.value) ? k.value : [0, 0, 0, 1];
          return v.map((n) => (typeof n === "number" ? n.toFixed(4) : "0")).join(", ");
        }).join(", ");
        return `    new THREE.QuaternionKeyframeTrack("${track.targetPart}.quaternion", [${times}], [${values}])`;
      }
      const times = track.keys.map((k) => (k.t * clip.durationMs / 1000).toFixed(3)).join(", ");
      const values = track.keys.map((k) => (typeof k.value === "number" ? k.value.toFixed(4) : "0")).join(", ");
      return `    new THREE.NumberKeyframeTrack("${track.targetPart}.${track.property}", [${times}], [${values}])`;
    });
    return `const ${moduleName}Clip${i} = new THREE.AnimationClip("${clip.name}", ${(clip.durationMs / 1000).toFixed(2)}, [\n${trackLines.join(",\n")}\n]);`;
  }).join("\n\n");

  const code = `import * as THREE from "three";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";

/**
 * Generated by motion-mcp on ${nowIso()}.
 * Prompt: ${escapeStr(input.planItem.interactionIdea)}
 */

${clipCode}

export function setup${moduleName}(modelUrl: string, scene: THREE.Scene): {
  mixer: THREE.AnimationMixer;
  update: (deltaTime: number) => void;
  play: (clipName?: string) => void;
  stop: () => void;
  dispose: () => void;
} {
  let mixer: THREE.AnimationMixer;
  let currentAction: THREE.AnimationAction | null = null;
  const clips = [${clips.map((_, i) => `${moduleName}Clip${i}`).join(", ")}];

  const loader = new GLTFLoader();
  loader.load(modelUrl, (gltf) => {
    scene.add(gltf.scene);
    mixer = new THREE.AnimationMixer(gltf.scene);
    const allClips = [...clips, ...gltf.animations];
    if (allClips.length > 0) {
      currentAction = mixer.clipAction(allClips[0]!);
      currentAction.play();
    }
  });

  return {
    get mixer() { return mixer; },
    update(deltaTime: number) { mixer?.update(deltaTime); },
    play(clipName?: string) {
      if (!mixer) return;
      currentAction?.stop();
      const allClips = [...clips];
      const clip = clipName ? allClips.find((c) => c.name === clipName) : allClips[0];
      if (clip) { currentAction = mixer.clipAction(clip); currentAction.play(); }
    },
    stop() { currentAction?.stop(); currentAction = null; },
    dispose() { mixer?.stopAllAction(); }
  };
}
`;

  return [{
    path: `.motion-mcp/generated/threejs/${moduleName}.ts`,
    mode: "create",
    content: code
  }];
}

function safeModuleName(file: string): string {
  const base = path.basename(file, path.extname(file));
  return base.replace(/[^a-zA-Z0-9]+/g, " ").split(" ").filter(Boolean)
    .map((p) => `${p.charAt(0).toUpperCase()}${p.slice(1)}`).join("") || "Generated";
}

function escapeStr(s: string): string {
  return s.replace(/\*/g, "").replace(/\n/g, " ").slice(0, 200);
}
