import path from "node:path";
import type { SceneArtboard } from "@motion-mcp/scene-graph";
import {
  type AssetInfo,
  type FileChange,
  type GenerateAnimationOptions,
  type MotionPlanItem,
  nowIso
} from "@motion-mcp/shared-types";

export function emitReactNativeAnimation(input: {
  planItem: MotionPlanItem;
  asset?: AssetInfo;
  options: GenerateAnimationOptions;
  scene?: SceneArtboard;
}): FileChange[] {
  const componentName = safeComponentName(input.asset?.path ?? input.planItem.file);
  return [
    {
      path: `.motion-mcp/generated/react-native/${componentName}.tsx`,
      mode: "create",
      content: emitComponent(componentName, input)
    }
  ];
}

function normalizeStateName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "") || "idle";
}

function emitComponent(
  componentName: string,
  input: {
    planItem: MotionPlanItem;
    asset?: AssetInfo;
    options: GenerateAnimationOptions;
    scene?: SceneArtboard;
  }
): string {
  const machine = input.scene?.stateMachines[0];
  const stateNames = machine?.states
    .map((state) => normalizeStateName(state.name))
    .filter(Boolean) ?? [];
  const states = Array.from(new Set(stateNames));
  const idToName = new Map(
    machine?.states.map((state) => [state.stateId, normalizeStateName(state.name)]) ?? []
  );
  const transitions: Record<string, Record<string, string>> = {};
  if (machine) {
    for (const transition of machine.transitions) {
      if (!transition.event) continue;
      const from = transition.fromStateId === "*" ? "*" : idToName.get(transition.fromStateId);
      const to = idToName.get(transition.toStateId);
      if (!from || !to) continue;
      transitions[from] = transitions[from] ?? {};
      transitions[from]![transition.event] = to;
    }
  }
  const initialState = (machine && idToName.get(machine.initialStateId)) || "idle";
  const stateUnion = states.length > 0
    ? states.map((state) => JSON.stringify(state)).join(" | ")
    : '"idle" | "hover" | "pressed" | "active" | "success" | "error" | "disabled"';
  const transitionsLiteral = states.length > 0
    ? `\nconst SCENE_TRANSITIONS: Record<string, Partial<Record<string, string>>> = ${JSON.stringify(transitions, null, 2)};\n`
    : "";
  const pathNodes = input.asset?.pathTree
    ?.flatMap(flattenNodes)
    .filter((node) => node.tag === "path" && typeof node.attrs.d === "string")
    .slice(0, 16) ?? [];
  const viewBox = input.asset?.dimensions?.viewBox ?? "0 0 160 160";
  const paths = pathNodes.length
    ? pathNodes.map((node, index) => emitAnimatedPath(node.attrs.d, node.semanticLabel ?? node.roleGuess, index)).join("\n")
    : emitAnimatedPath("M80 18C114 18 142 46 142 80S114 142 80 142 18 114 18 80 46 18 80 18Z", "fallback-orbit", 0);

  return `import * as React from "react";
import { AccessibilityInfo, Pressable } from "react-native";
import Svg, { Path } from "react-native-svg";
import Animated, {
  Easing,
  useAnimatedProps,
  useAnimatedStyle,
  useSharedValue,
  withSequence,
  withTiming
} from "react-native-reanimated";

const AnimatedPath = Animated.createAnimatedComponent(Path);

type MotionState = ${stateUnion};
type MotionEvent = "pointerEnter" | "pointerLeave" | "pressIn" | "pressOut" | "activate" | "success" | "error" | "reset";
${transitionsLiteral}
/**
 * Generated by motion-mcp on ${nowIso()}.
 * Prompt: ${escapeComment(input.planItem.interactionIdea)}
 * Source asset: ${input.asset?.path ?? "unknown"}
 * Runtime: host-code state machine + Reanimated 3 + react-native-svg.${machine ? `\n * SceneDoc artboard: ${input.scene?.artboardId}.` : ""}
 */
export interface ${componentName}Props {
  active?: boolean;
  onPress?: () => void;
  size?: number;
  color?: string;
  motionState?: MotionState;
}

export function ${componentName}({ active = false, onPress, size = 96, color = "#5B7CFA", motionState }: ${componentName}Props) {
  const [reducedMotion, setReducedMotion] = React.useState(false);
  const [localState, setLocalState] = React.useState<MotionState>(active ? "active" : "${initialState}");
  const state = motionState ?? localState;
  const progress = useSharedValue(active ? 1 : 0);
  const scale = useSharedValue(1);
  const shake = useSharedValue(0);

  React.useEffect(() => {
    AccessibilityInfo.isReduceMotionEnabled().then(setReducedMotion);
  }, []);

  React.useEffect(() => {
    progress.value = withTiming(state === "idle" || state === "disabled" ? 0 : 1, {
      duration: reducedMotion ? 0 : 460,
      easing: Easing.out(Easing.cubic)
    });
    if (!reducedMotion && state === "success") {
      scale.value = withSequence(withTiming(1.08, { duration: 140 }), withTiming(1, { duration: 260 }));
    }
    if (!reducedMotion && state === "error") {
      shake.value = withSequence(withTiming(-3, { duration: 60 }), withTiming(3, { duration: 80 }), withTiming(0, { duration: 100 }));
    }
  }, [state, progress, reducedMotion, scale, shake]);

  const send = (event: MotionEvent) => {
    if (motionState) return;
${states.length > 0 ? `    setLocalState((current) => {
      const next = SCENE_TRANSITIONS[current]?.[event] ?? SCENE_TRANSITIONS["*"]?.[event];
      return (next as MotionState | undefined) ?? current;
    });
    if (event === "pressIn" && !reducedMotion) scale.value = withTiming(0.94, { duration: 90 });
    if (event === "pressOut" && !reducedMotion) scale.value = withSequence(withTiming(1.06, { duration: 140 }), withTiming(1, { duration: 180 }));` : `
    if (event === "pressIn") {
      setLocalState("pressed");
      if (!reducedMotion) scale.value = withTiming(0.94, { duration: 90 });
    }
    if (event === "pressOut") {
      setLocalState(active ? "active" : "idle");
      if (!reducedMotion) scale.value = withSequence(withTiming(1.06, { duration: 140 }), withTiming(1, { duration: 180 }));
    }
    if (event === "activate") setLocalState("active");
    if (event === "success") setLocalState("success");
    if (event === "error") setLocalState("error");
    if (event === "reset") setLocalState("idle");`}
  };

  const shellStyle = useAnimatedStyle(() => ({
    opacity: state === "disabled" ? 0.48 : 1,
    transform: [{ translateX: shake.value }, { scale: scale.value }]
  }));

  const animatedProps = useAnimatedProps(() => ({
    strokeDashoffset: 220 - progress.value * 220,
    opacity: 0.68 + progress.value * 0.32
  }));

  return (
    <Pressable
      accessibilityRole="button"
      disabled={state === "disabled"}
      onPress={() => {
        send("activate");
        onPress?.();
      }}
      onPressIn={() => send("pressIn")}
      onPressOut={() => send("pressOut")}
    >
      <Animated.View style={shellStyle}>
        <Svg width={size} height={size} viewBox="${viewBox}">
${paths}
        </Svg>
      </Animated.View>
    </Pressable>
  );
}

export default ${componentName};
`;
}

function emitAnimatedPath(d: string | undefined, label: string, index: number): string {
  return `          {/* ${escapeComment(label)} */}
          <AnimatedPath
            d=${JSON.stringify(d ?? "")}
            fill="none"
            stroke={color}
            strokeWidth={4}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeDasharray={220}
            animatedProps={animatedProps}
            opacity={${Math.max(0.38, 1 - index * 0.04).toFixed(2)}}
          />`;
}

function flattenNodes<T extends { children: T[] }>(node: T): T[] {
  return [node, ...node.children.flatMap(flattenNodes)];
}

function safeComponentName(file: string): string {
  const base = path.basename(file, path.extname(file));
  const pascal = base
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");
  return `Motion${pascal || "Generated"}`;
}

function escapeComment(value: string): string {
  return value.replace(/\*\//g, "* /").replace(/\r?\n/g, " ");
}
